mdapipkg/unpackaged/objects/Apex_Trigger__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Criteria_Field_1__c</fullName>
        <label>Criteria Field 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Field_2__c</fullName>
        <label>Criteria Field 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Field_3__c</fullName>
        <label>Criteria Field 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Field_4__c</fullName>
        <label>Criteria Field 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Field_5__c</fullName>
        <label>Criteria Field 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Operator_1__c</fullName>
        <label>Criteria Operator 1</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Operator_2__c</fullName>
        <label>Criteria Operator 2</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Operator_3__c</fullName>
        <label>Criteria Operator 3</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Operator_4__c</fullName>
        <label>Criteria Operator 4</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Operator_5__c</fullName>
        <label>Criteria Operator 5</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Value_1__c</fullName>
        <label>Criteria Value 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Value_2__c</fullName>
        <label>Criteria Value 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Value_3__c</fullName>
        <label>Criteria Value 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Value_4__c</fullName>
        <label>Criteria Value 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria_Value_5__c</fullName>
        <label>Criteria Value 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Day_of_Month__c</fullName>
        <label>Day of Month</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Day_of_Week__c</fullName>
        <label>Day of Week</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hour__c</fullName>
        <label>Hour</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Minute__c</fullName>
        <label>Minute</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>00</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>01</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>02</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>03</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>04</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>05</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>06</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>07</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>08</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <label>09</label>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Apex Trigger</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Apex Trigger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Triggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/aspe_NewApexTriggerExtension.cls
public class aspe_NewApexTriggerExtension {
    public Apex_Trigger__c apexTrigger {get; set;}
    public String objectType {get; set;}
    public String minuteSelect;
    public String hourSelect;
    public String dayWeekSelect;
    public String dayMonthSelect;
    public String monthSelect;
    
    public String getMinuteSelect() {
        return this.apexTrigger.Minute__c;
    }

    public Void setMinuteSelect(String so) {
        so = so.replaceAll(',.+','');
        this.apexTrigger.Minute__c = so;
    }
    
    public List<String> getHourSelect() {
        List<String> stringReturn = new List<String>();
        if (this.apexTrigger.Hour__c != null) {
            for (String stringItem: this.apexTrigger.Hour__c.replaceAll('[\\[\\]]','').split(';')) {
                stringReturn.add(stringItem);
            }
        }
        return stringReturn;
    }

    public Void setHourSelect(String so) {
        so = so.replaceAll(', ',';');
        this.apexTrigger.Hour__c = so;
    }

    public List<String> getDayWeekSelect() {
        List<String> stringReturn = new List<String>();
        if (this.apexTrigger.Day_of_Week__c != null) {
            for (String stringItem: this.apexTrigger.Day_of_Week__c.replaceAll('[\\[\\]]','').split(';')) {
                stringReturn.add(stringItem);
            }
        }
        return stringReturn;
    }

    public Void setDayWeekSelect(String so) {
        so = so.replaceAll(', ',';');
        this.apexTrigger.Day_of_Week__c = so;
    }

    public List<String> getDayMonthSelect() {
        List<String> stringReturn = new List<String>();
        if (this.apexTrigger.Day_of_Month__c != null) {
            for (String stringItem: this.apexTrigger.Day_of_Month__c.replaceAll('[\\[\\]]','').split(';')) {
                stringReturn.add(stringItem);
            }
        }
        return stringReturn;
    }

    public Void setDayMonthSelect(String so) {
        so = so.replaceAll(', ',';');
        this.apexTrigger.Day_of_Month__c = so;
    }

    public List<String> getMonthSelect() {
        List<String> stringReturn = new List<String>();
        if (this.apexTrigger.Month__c != null) {
            for (String stringItem: this.apexTrigger.Month__c.replaceAll('[\\[\\]]','').split(';')) {
                stringReturn.add(stringItem);
            }
        }
        return stringReturn;
    }

    public Void setMonthSelect(String so) {
        so = so.replaceAll(', ',';');
        this.apexTrigger.Month__c = so;
    }
    
    public aspe_NewApexTriggerExtension(ApexPages.StandardController stdController) {
        this.apexTrigger = (Apex_Trigger__c)stdController.getRecord();
        this.apexTrigger.Minute__c = getDefaultValueAsString(Schema.SObjectType.Apex_Trigger__c.fields.Minute__c);
        this.apexTrigger.Hour__c = getDefaultValueAsString(Schema.SObjectType.Apex_Trigger__c.fields.Hour__c);
        this.apexTrigger.Day_of_Week__c = getDefaultValueAsString(Schema.SObjectType.Apex_Trigger__c.fields.Day_of_Week__c);
        this.apexTrigger.Day_of_Month__c = getDefaultValueAsString(Schema.SObjectType.Apex_Trigger__c.fields.Day_of_Month__c);
        this.apexTrigger.Month__c = getDefaultValueAsString(Schema.SObjectType.Apex_Trigger__c.fields.Month__c);
    }
    
    private String getDefaultValueAsString(Schema.DescribeFieldResult field) {
        List<Schema.PicklistEntry> pickVals = field.getPicklistValues();
        for (Schema.PicklistEntry pv: pickVals) {
            if (pv.isDefaultValue() && pv.isActive()) {
                return pv.getValue();
            }    
        }
        return '';
    }
    
	public static List<SelectOption> sortSelectOptionList(List<SelectOption> source) {
        List<string> sortable = new List<string>();
        for(SelectOption so: source) {
            // replace blank with '_!' so we know the final split will have two components
            sortable.Add((string.isblank(so.getLabel())?'_!':so.getLabel()) + '@!@' + (string.isblank(so.getValue())?'_!':so.getValue()));
        }
        // sort the list
        sortable.sort();
        List<SelectOption> targetList = new  List<SelectOption>();
        // split the value/name components and re create the list
        for(string s: sortable) {
                targetList.Add(new  SelectOption(s.split('@!@')[1].replace('_!',''), s.split('@!@')[0].replace('_!','')));
        }
        return targetList;
    }
    
    public List<SelectOption> getObjectTypeOptions() {
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        List<SelectOption> typeOptions = new List<SelectOption>();
        typeOptions.add(new SelectOption('','-Choose an object type-'));
        for (String key : gd.keySet()) {
            DescribeSObjectResult objectDescribe = gd.get(key).getDescribe();
            if (objectDescribe.isAccessible() && objectDescribe.isQueryable()) {
            	typeOptions.add(new SelectOption(key,objectDescribe.getLabel()+' ('+objectDescribe.getName()+')'));
            }
        }
        typeOptions = sortSelectOptionList(typeOptions);
        return typeOptions;
    }
    
    public Boolean getNoSelectedObject() {
        if (apexTrigger.Object_Type__c == '' || apexTrigger.Object_Type__c == null) return true;
        else return false;
    }
    
    public List<SelectOption> getFieldOptions() {
    	List<SelectOption> fieldOptions = new List<SelectOption>();
        fieldOptions.add(new SelectOption('','-Select a field-'));
        
        if (!getNoSelectedObject()) {
            Map<String, Schema.SObjectField> fields = Schema.describeSObjects(
                new List<String>{apexTrigger.Object_Type__c}
            	)[0].fields.getMap();
            for (String key : fields.keySet()) {
                DescribeFieldResult fieldDescribe = fields.get(key).getDescribe();
                if (fieldDescribe.isAccessible()) {
                    fieldOptions.add(new SelectOption(key,fieldDescribe.getLabel()+' ('+fieldDescribe.getName()+')'));
                }
            }
        } else {
            fieldOptions.add(new SelectOption('','Select an object type first'));
        }
        
        fieldOptions = sortSelectOptionList(fieldOptions);
        return fieldOptions;
    }
    public List<SelectOption> getOperatorOptions1() {
        return operatorOptions(1);
    }
    public List<SelectOption> getOperatorOptions2() {
        return operatorOptions(2);
    }
    public List<SelectOption> getOperatorOptions3() {
        return operatorOptions(3);
    }
    public List<SelectOption> getOperatorOptions4() {
        return operatorOptions(4);
    }
    public List<SelectOption> getOperatorOptions5() {
        return operatorOptions(5);
    }
    
    public List<SelectOption> operatorOptions(Integer num) {
        String criteriaField;
        if (num == 1) criteriaField = apexTrigger.Criteria_Field_1__c;
        if (num == 2) criteriaField = apexTrigger.Criteria_Field_2__c;
        if (num == 3) criteriaField = apexTrigger.Criteria_Field_3__c;
        if (num == 4) criteriaField = apexTrigger.Criteria_Field_4__c;
        if (num == 5) criteriaField = apexTrigger.Criteria_Field_5__c;
        
    	List<SelectOption> operatorOptions = new List<SelectOption>();
        operatorOptions.add(new SelectOption('','-Select an operator-'));
        operatorOptions.add(new SelectOption('=','Equals'));
        operatorOptions.add(new SelectOption('!=','Does Not Equal'));
        operatorOptions.add(new SelectOption('IS NULL','Is Empty'));
        operatorOptions.add(new SelectOption('IS NOT NULL','Is Not Empty'));
        
        String fieldType = '';
        
        if (!getNoSelectedObject() && criteriaField != null && criteriaField != '') {
            Schema.SObjectField field = Schema.describeSObjects(
                new List<String>{apexTrigger.Object_Type__c}
            	)[0].fields.getMap().get(criteriaField);
            if (field != null) fieldType = field.getDescribe().getType().name();
            switch on fieldType {
                when 'COMBOBOX' {
                    
                }
                when 'CURRENCY' {
        			operatorOptions.add(new SelectOption('>','Greater Than'));
        			operatorOptions.add(new SelectOption('>=','Greater Than or Equal To'));
        			operatorOptions.add(new SelectOption('<','Less Than'));
        			operatorOptions.add(new SelectOption('<=','Less Than or Equal To'));
                }
                when 'DATE' {
        			operatorOptions.add(new SelectOption('>','Greater Than'));
        			operatorOptions.add(new SelectOption('>=','Greater Than or Equal To'));
        			operatorOptions.add(new SelectOption('<','Less Than'));
        			operatorOptions.add(new SelectOption('<=','Less Than or Equal To'));
                    
                }
                when 'DATETIME' {
        			operatorOptions.add(new SelectOption('>','Greater Than'));
        			operatorOptions.add(new SelectOption('>=','Greater Than or Equal To'));
        			operatorOptions.add(new SelectOption('<','Less Than'));
        			operatorOptions.add(new SelectOption('<=','Less Than or Equal To'));
                    
                }
                when 'DOUBLE' {
        			operatorOptions.add(new SelectOption('>','Greater Than'));
        			operatorOptions.add(new SelectOption('>=','Greater Than or Equal To'));
        			operatorOptions.add(new SelectOption('<','Less Than'));
        			operatorOptions.add(new SelectOption('<=','Less Than or Equal To'));
                    
                }
                when 'EMAIL' {
        			operatorOptions.add(new SelectOption('contains','Contains'));
        			operatorOptions.add(new SelectOption('starts_with','Starts With'));
        			operatorOptions.add(new SelectOption('ends_with','Ends With'));
                    
                }
                when 'ID' {
                    
                }
                when 'INTEGER' {
        			operatorOptions.add(new SelectOption('>','Greater Than'));
        			operatorOptions.add(new SelectOption('>=','Greater Than or Equal To'));
        			operatorOptions.add(new SelectOption('<','Less Than'));
        			operatorOptions.add(new SelectOption('<=','Less Than or Equal To'));
                    
                }
                when 'MULTIPICKLIST' {
                    
                }
                when 'PERCENT' {
        			operatorOptions.add(new SelectOption('>','Greater Than'));
        			operatorOptions.add(new SelectOption('>=','Greater Than or Equal To'));
        			operatorOptions.add(new SelectOption('<','Less Than'));
        			operatorOptions.add(new SelectOption('<=','Less Than or Equal To'));
                    
                }
                when 'PHONE' {
        			operatorOptions.add(new SelectOption('contains','Contains'));
        			operatorOptions.add(new SelectOption('starts_with','Starts With'));
        			operatorOptions.add(new SelectOption('ends_with','Ends With'));
                    
                }
                when 'PICKLIST' {
        			operatorOptions.add(new SelectOption('contains','Contains'));
        			operatorOptions.add(new SelectOption('starts_with','Starts With'));
        			operatorOptions.add(new SelectOption('ends_with','Ends With'));
                    
                }
                when 'STRING' {
        			operatorOptions.add(new SelectOption('contains','Contains'));
        			operatorOptions.add(new SelectOption('starts_with','Starts With'));
        			operatorOptions.add(new SelectOption('ends_with','Ends With'));
                    
                }
                when 'TEXTAREA' {
        			operatorOptions.add(new SelectOption('contains','Contains'));
        			operatorOptions.add(new SelectOption('starts_with','Starts With'));
        			operatorOptions.add(new SelectOption('ends_with','Ends With'));
                    
                }
                when 'TIME' {
        			operatorOptions.add(new SelectOption('>','Greater Than'));
        			operatorOptions.add(new SelectOption('>=','Greater Than or Equal To'));
        			operatorOptions.add(new SelectOption('<','Less Than'));
        			operatorOptions.add(new SelectOption('<=','Less Than or Equal To'));
                    
                }
                when 'URL' {
        			operatorOptions.add(new SelectOption('contains','Contains'));
        			operatorOptions.add(new SelectOption('starts_with','Starts With'));
        			operatorOptions.add(new SelectOption('ends_with','Ends With'));
                    
                }
            }
        }
        
        return operatorOptions;
    }
    
    public List<SelectOption> getMinuteOptions() {
        List<SelectOption> options = new List<SelectOption>();
        for(PicklistEntry option: Apex_Trigger__c.Minute__c.getDescribe().getPicklistValues()) {
            options.add(new SelectOption(option.getValue(),option.getLabel()));
        }
        
        return options;
    }
    
    public List<SelectOption> getHourOptions() {
        List<SelectOption> options = new List<SelectOption>();
        for(PicklistEntry option: Apex_Trigger__c.Hour__c.getDescribe().getPicklistValues()) {
            options.add(new SelectOption(option.getValue(),option.getLabel()));
        }
        
        return options;
    }
    
    public List<SelectOption> getDayWeekOptions() {
        List<SelectOption> options = new List<SelectOption>();
        for(PicklistEntry option: Apex_Trigger__c.Day_of_Week__c.getDescribe().getPicklistValues()) {
            options.add(new SelectOption(option.getValue(),option.getLabel()));
        }
        
        return options;
    }
    
    public List<SelectOption> getDayMonthOptions() {
        List<SelectOption> options = new List<SelectOption>();
        for(PicklistEntry option: Apex_Trigger__c.Day_of_Month__c.getDescribe().getPicklistValues()) {
            options.add(new SelectOption(option.getValue(),option.getLabel()));
        }
        
        return options;
    }
    
    public List<SelectOption> getMonthOptions() {
        List<SelectOption> options = new List<SelectOption>();
        for(PicklistEntry option: Apex_Trigger__c.Month__c.getDescribe().getPicklistValues()) {
            options.add(new SelectOption(option.getValue(),option.getLabel()));
        }
        
        return options;
    }

    private Boolean validateCriteria(Integer num) {
        String field = '';
        String operator = '';
        String value = '';
        if (num == 1) {
            field = apexTrigger.Criteria_Field_1__c;
            operator = apexTrigger.Criteria_Operator_1__c;
            value = apexTrigger.Criteria_Value_1__c;
        }
        if (num == 2) {
            field = apexTrigger.Criteria_Field_2__c;
            operator = apexTrigger.Criteria_Operator_2__c;
            value = apexTrigger.Criteria_Value_2__c;
        }
        if (num == 3) {
            field = apexTrigger.Criteria_Field_3__c;
            operator = apexTrigger.Criteria_Operator_3__c;
            value = apexTrigger.Criteria_Value_3__c;
        }
        if (num == 4) {
            field = apexTrigger.Criteria_Field_4__c;
            operator = apexTrigger.Criteria_Operator_4__c;
            value = apexTrigger.Criteria_Value_4__c;
        }
        if (num == 5) {
            field = apexTrigger.Criteria_Field_5__c;
            operator = apexTrigger.Criteria_Operator_5__c;
            value = apexTrigger.Criteria_Value_5__c;
        }
        if ((field == null || field == '') && (operator == null || operator == '') && ( value == null || value == '')) return true;
        if (field != null && field != '' && operator != null && operator != '' && value != null && value != '') {
            Boolean listContainsOperator = false;
            for (SelectOption so: operatorOptions(num)) {
                if (so.getValue() == operator) listContainsOperator = true;
            }
            if (!listContainsOperator) return false;
            return true;
        }
        return false;
    }

    private Boolean validate() {
        if (!this.apexTrigger.Active__c) return true;
        if (getNoSelectedObject()) return false;
        for (Integer i = 1; i<=5; i++) {
            if (!validateCriteria(i)) return false;
        }
        return true;
    }

    public PageReference save() {
        Boolean valid = validate();
        if (!valid) return null;
        upsert this.apexTrigger;
        PageReference pageRef = new PageReference('/'+this.apexTrigger.id);
        return pageRef;
    }
}